import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Pastes text at the cursor in the app in front, the way Wispr Flow does: Patter puts the text on
/// the clipboard, presses Command-V, and puts the previous clipboard contents back half a second
/// later. Clipboard managers do not save the text, because Patter marks it as transient.
@MainActor
enum Paster {
    /// Remote desktop and virtual machine apps send the clipboard to the other computer before
    /// they paste, so Patter waits longer before it puts the clipboard back.
    private static let remoteApps: Set<String> = [
        "com.microsoft.rdc.macos", "com.apple.ScreenSharing", "com.citrix.receiver.nomas",
        "com.vmware.horizon", "com.vmware.fusion", "com.parallels.desktop.console", "com.utmapp.UTM",
    ]

    private struct PendingRestore {
        let snapshot: ClipboardSnapshot
        /// The clipboard change count right after Patter wrote the text.
        let changeCount: Int
        let task: Task<Void, Never>
    }

    private static var pending: PendingRestore?

    /// Returns false if the cursor is not in a text field. Then the text stays on the clipboard.
    static func paste(_ text: String) async -> Bool {
        guard let app = NSWorkspace.shared.frontmostApplication else {
            Clipboard.copy(text)
            return false
        }
        let pid = app.processIdentifier
        let focus = await Task.detached { FocusedElement.inspect(pid: pid) }.value
        guard focus.kind != .notText else {
            Clipboard.copy(text)
            return false
        }
        await waitForModifierRelease()

        let pasteboard = NSPasteboard.general
        let previous: ClipboardSnapshot
        if let pending, pending.changeCount == pasteboard.changeCount {
            // The clipboard still holds the text of the paste before: keep the contents from before that paste.
            pending.task.cancel()
            previous = pending.snapshot
        } else {
            pending?.task.cancel()
            previous = ClipboardSnapshot(pasteboard)
        }

        writeTransient(text, to: pasteboard)
        let changeCount = pasteboard.changeCount
        Keyboard.pressCommandV()

        let delay: Duration = remoteApps.contains(app.bundleIdentifier ?? "") ? .seconds(5) : .milliseconds(500)
        let task = Task {
            try? await Task.sleep(for: delay)
            guard !Task.isCancelled else { return }
            // If the user copied something in the meantime, keep it.
            if pasteboard.changeCount == changeCount { previous.restore(to: pasteboard) }
            pending = nil
        }
        pending = PendingRestore(snapshot: previous, changeCount: changeCount, task: task)
        return true
    }

    /// Writes the text with the markers from nspasteboard.org that tell clipboard managers to skip it.
    private static func writeTransient(_ text: String, to pasteboard: NSPasteboard) {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString("com.unculture.Patter", forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
    }

    /// Waits up to one second until the user releases the shortcut keys, so that the app gets
    /// Command-V and not, for example, Control-Command-V.
    private static func waitForModifierRelease() async {
        let modifiers: CGEventFlags = [.maskControl, .maskShift, .maskAlternate, .maskCommand]
        for _ in 0..<40 {
            if CGEventSource.flagsState(.hidSystemState).isDisjoint(with: modifiers) { return }
            try? await Task.sleep(for: .milliseconds(25))
        }
    }
}

/// A copy of everything on the clipboard, so that Patter can put it back after a paste.
struct ClipboardSnapshot {
    /// The types of each item in their original order, because apps use the first type they can read.
    private let items: [[(type: NSPasteboard.PasteboardType, data: Data)]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
        }
    }

    /// A password manager clears a password from the clipboard after a time. It cannot do that for
    /// a copy that Patter puts back, so Patter does not put back a password.
    var holdsPassword: Bool {
        items.contains { $0.contains { $0.type.rawValue == "org.nspasteboard.ConcealedType" } }
    }

    func restore(to pasteboard: NSPasteboard) {
        guard !holdsPassword else { return }
        pasteboard.clearContents()
        let copies = items.map { entries in
            let item = NSPasteboardItem()
            for entry in entries { item.setData(entry.data, forType: entry.type) }
            return item
        }
        if !copies.isEmpty { pasteboard.writeObjects(copies) }
    }
}

/// Finds out whether the keyboard focus of an app is in a text field. Patter reads only the type
/// of the focused element, never its text.
enum FocusedElement {
    enum Kind: Sendable {
        case text
        case notText
        /// The app does not tell. Terminals and Electron apps often draw their own text views.
        case unknown
    }

    struct Focus: Sendable {
        var kind: Kind
        /// The role and the subrole, for example "AXTextField/AXSearchField". For the developer test.
        var role: String
    }

    private static let textRoles: Set<String> = ["AXTextField", "AXTextArea", "AXComboBox", "AXSearchField"]

    /// Elements that cannot take a paste. Other roles, for example groups and windows, count as
    /// unknown, and Patter pastes there.
    private static let nonTextRoles: Set<String> = [
        "AXButton", "AXCheckBox", "AXRadioButton", "AXPopUpButton", "AXMenuButton", "AXDisclosureTriangle",
        "AXSlider", "AXImage", "AXStaticText", "AXLink", "AXList", "AXOutline", "AXBrowser",
        "AXMenu", "AXMenuItem", "AXWebArea",
    ]

    /// Asks the app over the Accessibility API. A busy app gets half a second to answer.
    static func inspect(pid: pid_t) -> Focus {
        let app = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(app, 0.5)
        guard let focused: AXUIElement = value(kAXFocusedUIElementAttribute, of: app) else {
            return Focus(kind: .unknown, role: "none")
        }
        AXUIElementSetMessagingTimeout(focused, 0.5)
        let role: String = value(kAXRoleAttribute, of: focused) ?? "unknown"
        let subrole: String? = value(kAXSubroleAttribute, of: focused)
        let description = [role, subrole].compactMap { $0 }.joined(separator: "/")

        if textRoles.contains(role) {
            return Focus(kind: .text, role: description)
        }
        // A web page or an Electron app reports this for an element in a rich text editor.
        let inEditor: AXUIElement? = value("AXEditableAncestor", of: focused)
        // Custom text views report a value that the app lets other apps change, and a character count.
        var settable: DarwinBoolean = false
        let editable = AXUIElementIsAttributeSettable(focused, kAXValueAttribute as CFString, &settable) == .success
            && settable.boolValue
            && (value(kAXNumberOfCharactersAttribute, of: focused) as CFNumber?) != nil
        if inEditor != nil || editable {
            return Focus(kind: .text, role: description)
        }
        return Focus(kind: nonTextRoles.contains(role) ? .notText : .unknown, role: description)
    }

    private static func value<T>(_ attribute: String, of element: AXUIElement) -> T? {
        var result: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, attribute as CFString, &result) == .success else { return nil }
        return result as? T
    }
}

enum Keyboard {
    /// Presses Command-V. The key comes from the keyboard layout, so that the paste also works
    /// with a layout such as Dvorak, where V is on a different key.
    @MainActor
    static func pressCommandV() {
        let source = CGEventSource(stateID: .hidSystemState)
        let command = CGKeyCode(kVK_Command)
        let v = keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        let events: [(CGKeyCode, Bool, CGEventFlags)] = [
            (command, true, .maskCommand), (v, true, .maskCommand), (v, false, .maskCommand), (command, false, []),
        ]
        for (key, down, flags) in events {
            let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: down)
            event?.flags = flags
            event?.post(tap: .cghidEventTap)
        }
    }

    /// The key that types the character while Command is down. Text Input Sources work only on the main thread.
    @MainActor
    static func keyCode(for character: String) -> CGKeyCode? {
        let layouts = layoutData([TISCopyCurrentKeyboardLayoutInputSource(), TISCopyCurrentASCIICapableKeyboardLayoutInputSource()])
        for layout in layouts {
            for code in 0..<128 where translate(code, modifiers: cmdKey, in: layout) == character {
                return CGKeyCode(code)
            }
        }
        return nil
    }

    /// The character that the key types without modifier keys, to show it in a shortcut. Like the
    /// menus, it uses the ASCII-capable layout, so that a Russian layout shows R and not К.
    @MainActor
    static func character(for keyCode: Int) -> String? {
        guard let layout = layoutData([TISCopyCurrentASCIICapableKeyboardLayoutInputSource()]).first,
              let text = translate(keyCode, modifiers: 0, in: layout),
              !text.unicodeScalars.contains(where: CharacterSet.controlCharacters.contains)
        else { return nil }
        return text
    }

    @MainActor
    private static func layoutData(_ sources: [Unmanaged<TISInputSource>?]) -> [Data] {
        sources.compactMap { source in
            guard let source = source?.takeRetainedValue(),
                  let pointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
            else { return nil }
            return Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
        }
    }

    /// The text that the key types in the layout while the modifier keys (Carbon flags) are down.
    private static func translate(_ keyCode: Int, modifiers: Int, in layout: Data) -> String? {
        layout.withUnsafeBytes { buffer in
            guard let keyboard = buffer.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
            var deadKeys: UInt32 = 0
            var length = 0
            var characters = [UniChar](repeating: 0, count: 4)
            let status = UCKeyTranslate(
                keyboard, UInt16(keyCode), UInt16(kUCKeyActionDown), UInt32((modifiers >> 8) & 0xFF),
                UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysMask),
                &deadKeys, characters.count, &length, &characters)
            guard status == noErr, length > 0 else { return nil }
            return String(utf16CodeUnits: characters, count: length)
        }
    }
}
